from .MainMenu import Ui_MainMenuWindow
from .ActivityLogWindow import Ui_ActivityLogWindow
from .DeleteUserWidget import Ui_DeleteUserWidget
from .DroneWindow import Ui_DroneWindow
from .IncidentReport import Ui_IncidentReportWindow
from .InsertUserWidget import Ui_InsertUserWidget
from .MessageWidget import Ui_MessageWidget
from .NotificationWidget import Ui_NotificationWidget
from .PINEntryWidget import Ui_PINEntryWidget
from .SilentAlarmWidget import Ui_SilentAlarmWidget
